name: 'dbt_ynab'
version: '1.0.0'

profile: 'dbt_ynab'

model-paths: ["models", "sources"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
- "target"
- "dbt_packages"

models:
  dbt_ynab:
    +materialized: external
