dbt_ynab:
  outputs:
    dev:
      type: duckdb
      external_root: target/output

      settings:
        # avoid builtin httpfs extension being autoloaded
        autoload_known_extensions: false

      extensions:
      - json

      filesystems:
      # https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.implementations.http.HTTPFileSystem
      - fs: https

        # https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientSession.request
        headers:
          Authorization: "Bearer {{ env_var('DBT_ENV_SECRET_YNAB_API_TOKEN') }}"

  target: dev
